### ISSUE TITLE
ApplePayButton not showing on simulator

### ISSUE THREAD

**Issue by moatazfouad** [google-pay/flutter-plugin#171] opened 2022-11-13 06:23 UTC
`ApplePayButton` widget does not appear on simulator at all.
I tried to see related issues where I got that maybe happen due to the county code or something like that,
so I used the `default_config_apple_pay.json` in the example project and still the same issue..
how can I fix that please or what is the issue?

**Comment by JlUgia** [comment] 2022-11-14 15:41
Hi @moatazfouad this is a duplicate of #104 and #116.
What country are you operating from?
See [additional info in this post](https://stackoverflow.com/questions/43120587/apple-pay-works-on-simulator-but-not-on-device).

Please, use the other issues going forward.

**Closed by JlUgia** 2022-11-14 15:41 UTC
