### ISSUE TITLE
General] Payment request is invalid: Error Domain=PKPassKitErrorDomain 

### ISSUE THREAD

**Issue by dalton5** [google-pay/flutter-plugin#100] opened 2021-10-24 14:37 UTC
Hi,

I use apple pay with the plugin flutter_stripe.

When I pay with Apple pay in the currency of my card (€). Apple pay is loading and works.

When I pay with Apple pay in another currency ($) Apple pay is raising an error in my debug log.

General] Payment request is invalid: Error Domain=PKPassKitErrorDomain Code=1 "Invalid in-app payment request" UserInfo={NSLocalizedDescription=Invalid in-app payment request, NSUnderlyingError=0x281bd8c00 {Error Domain=PKPassKitErrorDomain Code=1 "PKPaymentRequest must contain a property 'countryCode' of type 'NSString'

I think it's a bug in the plugin.

Can you please check?

Is it a known bug?

Is there a workaround?

Thanks,

**Comment by JlUgia** [comment] 2021-11-02 12:43
If you look at the error in detail, it looks like you are missing the `countryCode` property. Have you set it in the payment configuration file appropriately? (see [example](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json#L8)].

**Comment by JlUgia** [comment] 2021-11-18 16:32
Closing this issue since the cause was identified.
Feel free to reopen if the issue persists.

**Closed by JlUgia** 2021-11-18 16:32 UTC
