### ISSUE TITLE
Question: Is this plugin supporting UPI payments in India?

### ISSUE THREAD

**Issue by abinvs-2019** [google-pay/flutter-plugin#224] opened 2023-10-10 06:38 UTC
Is this plugin supporting the UPI services in India, Could not find any docs regarding the integrations. 
Like -> Clicking on gpay button -> Gpay app opened -> Payment done -> Return status to flutter. Is there a way to impliment this flow?

**Comment by JlUgia** [comment] 2023-12-19 22:17
Duplicate of #231.

**Closed by JlUgia** 2023-12-19 22:17 UTC
