### ISSUE TITLE
Connect to Backend

### ISSUE THREAD

**Issue by wazini-john** [google-pay/flutter-plugin#57] opened 2021-06-13 15:39 UTC
How do I use the `paymentResult` to carry out the necessary transactions and send relevant info to my backend ?

**Comment by JlUgia** [comment] 2021-06-15 12:21
Hi @wazini-john, this varies depending on the payment processor you use.
You can typically find a section about Google Pay in the [developer documentation for your processor](https://g.co/pay/processors). Some other PSPs integrate directly with this plugin or provide convenience accessors within their libraries and SDKs to make this step easier.

What processor are you using?

**Comment by wazini-john** [comment] 2021-06-15 13:17
Paypal

**Comment by JlUgia** [comment] 2021-06-15 13:26
At the moment, this plugin only supports Apple Pay on iOS and Google Pay on Android.
As far as I know, an [Apple Pay saved card can't be used to create an order with PayPal](https://developer.apple.com/apple-pay/payment-platforms/). If what you are rather thinking about is having support for a PayPal button as part of this plugin, please feel free to create an issue or start a discussion about the potential feature request.

**Comment by wazini-john** [comment] 2021-06-15 13:28
after reading through the list, we've picked mastercard payment gateway

**Comment by JlUgia** [comment] 2021-06-16 10:00
Okay. Payment providers have diverse sets of features. Be sure to pick one that fits your needs, looking at characteristics like country support, payment schemes (eg.: online payment, marketplace, recurring billing), fees, additional features (eg..: reports, risk tools), or support for your favourite programming languages among others.

Feel free to close this one if the issue is addressed.

**Comment by wazini-john** [comment] 2021-06-16 12:49
Is there one recommended by  Google

**Comment by JlUgia** [comment] 2021-06-25 07:40
No, we don't. We think that you are in the best position to determine what PSP is the right one for you.
Have you picked one yet? You can find guidance on how to use the Google Pay token in the documentation for your PSP.
In addition, we are working on a set of backend samples to illustrate how to handle the payment result and send it to your PSP, that we'll publish soon.

Feel free to close the issue if your question has been addressed.

**Comment by JlUgia** [comment] 2021-07-21 13:09
Closing this due to inactivity.
Feel free to reopen if you have additional questions.

**Closed by JlUgia** 2021-07-21 13:09 UTC

**Comment by omidraha** [comment] 2021-08-05 21:23
Hi
I created a payment profile in my Google Developer account.
And in the payment profile now I see a `Merchant ID`.

Now my question is where do I get the `gateway` value?
Do I have to register elsewhere?
Or I can put any of the values listed [here](https://developers.google.com/pay/api/android/reference/request-objects#gateway).

**Comment by JlUgia** [comment] 2021-09-12 22:09
Hi @omidraha, Google Pay and Apple Pay need external payment gateways in order to process payments.
Here's a [list of supported processors for Google Pay](https://g.co/pay/processors) and [Apple Pay](https://developer.apple.com/apple-pay/payment-platforms/).

You can find the details of the payment gateway, directly in their admin/configuration sites.
