### ISSUE TITLE
Execution failed for task ':pay_android:compileDebugKotlin'.

### ISSUE THREAD

**Issue by nipun0212** [google-pay/flutter-plugin#31] opened 2021-05-22 16:25 UTC
After adding pay to pubspec.yaml, the deployment is failing with below error

pub-cache/hosted/pub.dartlang.org/pay_android-1.0.1/android/src/main/kotlin/io/flutter/plugins/pay_android/GooglePayHandler.kt: (112, 27): Expecting a parameter declaration
pub-cache/hosted/pub.dartlang.org/pay_android-1.0.1/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (37, 28): Expecting a parameter declaration
pub-cache/hosted/pub.dartlang.org/pay_android-1.0.1/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (53, 52): Expecting a parameter declaration
pub-cache/hosted/pub.dartlang.org/pay_android-1.0.1/android/src/main/kotlin/io/flutter/plugins/pay_android/PayPlugin.kt: (38, 79): Expecting a parameter declaration
pub-cache/hosted/pub.dartlang.org/pay_android-1.0.1/android/src/main/kotlin/io/flutter/plugins/pay_android/PayPlugin.kt: (52, 67): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pay_android:compileDebugKotlin'.

**Comment by JlUgia** [comment] 2021-05-24 16:48
Hi nipun0212, this is a duplicate of #29. Please, take a look at it.
I'm creating a new issue to include that configuration in the documentation.

**Comment by nipun0212** [comment] 2021-05-25 10:02
That helped @JlUgia . Thanks. Closing the issue.

**Closed** 2021-09-12 20:41 UTC
