### ISSUE TITLE
function [Pay.showPaymentSelector] does not return if I close the payment sheet

### ISSUE THREAD

**Issue by xmany** [google-pay/flutter-plugin#90] opened 2021-09-14 01:00 UTC
Hi guys,

I am using the plugin within my own UI, thus I am using the function [Pay.showPaymentSelector]. 

on iOS, when the payment sheet is brought up, user can tap "cancel" button on the top right corner of the sheet. when I do that, the function does not return immediately, instead it will hang there indefinitely. I have no way of knowing this "cancellation" action and doing something about it.

So I had to timeout the Future... it is not a good solution.

Am I missing something or is it a bug?

BTW, if I don't cancel, the function can proceed as normal and the return value can be converted into stripe token successfully. So I guess the flow should be correct.

Following up, this happens on Android as well, where I can drag to dismiss the payment sheet.

**Comment by xmany** [comment] 2021-09-14 01:57
Looks like there's a PR addressing this issue already [https://github.com/google-pay/flutter-plugin/pull/82]

Can someone please merge the PR pls...

**Comment by JlUgia** [comment] 2021-10-04 14:13
The PR has been merged and a new version is out. Take a look at [1.0.6](https://pub.dev/packages/pay/versions/1.0.6).

**Comment by JlUgia** [comment] 2021-10-06 08:04
Closing. Feel free to reopen if the issue is not resolved on your end.

**Closed by JlUgia** 2021-10-06 08:04 UTC
