### ISSUE TITLE
I am using pay 1.0.5 package for integrating google pay my app. Currently I m working in test environment. I am providing the default_payment_profile_google_pay.json as a parameter for paymentConfigurationAsset inside GooglePayButton, but the pay button is not displaying. Also, childOnError is being triggered. I don't know what the error is and how to fix it and show googlePayButton

### ISSUE THREAD

**Issue by Ashish-1008** [google-pay/flutter-plugin#64] opened 2021-06-22 09:36 UTC

**Comment by JlUgia** [comment] 2021-06-22 15:27
(Duplicate of #48)
Hi @Ashish-1008, it seems that there is an error in your configuration. Take a look at the logs, filtering for `WalletMerchantError` to learn about the concrete cause. You can check them on Android Studio (or other IDE), or directly using the terminal: `adb -d logcat -s WalletMerchantError`.

**Comment by JlUgia** [comment] 2021-07-21 13:07
Closing this due to inactivity.
Feel free to reopen if the issue persists.

**Closed by JlUgia** 2021-07-21 13:07 UTC

**Comment by tijnar** [comment] 2021-08-06 08:08
I am getting the same issue.

**Comment by abdalazeez1** [comment] 2021-09-27 04:23
i am getting the same issue
